version: '3.8'

services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: empleados_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - empleados_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de la aplicación Spring Boot
  app:
    build: .
    container_name: empleados_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5003:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/empleados_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - empleados_network

# Volúmenes
volumes:
  postgres_data:
    driver: local

# Redes
networks:
  empleados_network:
    driver: bridge